services:
  db:
    image: postgres:latest
    container_name: Hack2025
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql